[package]
name = "ip-xact-rs"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.22"
roxmltree = "0.20.0"
walkdir = "2.5.0"
